In [1]:
import numpy as np
import random
import torch

Создайте случайный FloatTensor размера 3x4x5

In [9]:
a = torch.rand(size=(3,4,5), dtype = torch.float)
a

tensor([[[0.1006, 0.6363, 0.4298, 0.4317, 0.7891],
         [0.3076, 0.5376, 0.6636, 0.4882, 0.0555],
         [0.7071, 0.0301, 0.0575, 0.3846, 0.2239],
         [0.1454, 0.9682, 0.6252, 0.7655, 0.2429]],

        [[0.7099, 0.4587, 0.8965, 0.1306, 0.4174],
         [0.4268, 0.2829, 0.7791, 0.2872, 0.7466],
         [0.6718, 0.9089, 0.8003, 0.0368, 0.4725],
         [0.5360, 0.5384, 0.2267, 0.3895, 0.7857]],

        [[0.0885, 0.8162, 0.5524, 0.7393, 0.0087],
         [0.5118, 0.1334, 0.1096, 0.7831, 0.4330],
         [0.2108, 0.7885, 0.6833, 0.5605, 0.4768],
         [0.3881, 0.1233, 0.5831, 0.9115, 0.8352]]])

Выведите его форму (shape)

In [11]:
a.size()

torch.Size([3, 4, 5])

Приведите его к форме 6х10

In [25]:
a = a.reshape(6,10)
a

tensor([[0.1006, 0.6363, 0.4298, 0.4317, 0.7891, 0.3076, 0.5376, 0.6636, 0.4882,
         0.0555],
        [0.7071, 0.0301, 0.0575, 0.3846, 0.2239, 0.1454, 0.9682, 0.6252, 0.7655,
         0.2429],
        [0.7099, 0.4587, 0.8965, 0.1306, 0.4174, 0.4268, 0.2829, 0.7791, 0.2872,
         0.7466],
        [0.6718, 0.9089, 0.8003, 0.0368, 0.4725, 0.5360, 0.5384, 0.2267, 0.3895,
         0.7857],
        [0.0885, 0.8162, 0.5524, 0.7393, 0.0087, 0.5118, 0.1334, 0.1096, 0.7831,
         0.4330],
        [0.2108, 0.7885, 0.6833, 0.5605, 0.4768, 0.3881, 0.1233, 0.5831, 0.9115,
         0.8352]])

Создайте случайный IntTensor размера 10

In [22]:
b = torch.randint(size=(10,), high=100)
b

tensor([18, 64, 44, 72, 23,  3, 24, 79, 18, 35])

Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [26]:
mult = a.mul(b)
mult

tensor([[ 1.8103, 40.7262, 18.9125, 31.0858, 18.1495,  0.9228, 12.9012, 52.4226,
          8.7875,  1.9432],
        [12.7285,  1.9289,  2.5299, 27.6944,  5.1501,  0.4361, 23.2379, 49.3935,
         13.7781,  8.5027],
        [12.7783, 29.3566, 39.4446,  9.4063,  9.6007,  1.2804,  6.7902, 61.5459,
          5.1699, 26.1311],
        [12.0921, 58.1702, 35.2126,  2.6503, 10.8682,  1.6079, 12.9222, 17.9132,
          7.0102, 27.5010],
        [ 1.5932, 52.2382, 24.3038, 53.2277,  0.1993,  1.5353,  3.2026,  8.6614,
         14.0960, 15.1556],
        [ 3.7936, 50.4651, 30.0638, 40.3539, 10.9667,  1.1642,  2.9599, 46.0683,
         16.4063, 29.2333]])

Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти

In [34]:
c = mult.matmul(mult.T)
c

tensor([[6311.7344, 4130.9595, 5842.7510, 4558.8276, 4898.3472, 6739.4312],
        [4130.9595, 4207.6855, 4120.7476, 2000.7770, 2483.6555, 4215.1240],
        [5842.7510, 4120.7476, 7306.8350, 5327.5752, 4040.8374, 6906.3086],
        [4558.8276, 2000.7770, 5327.5752, 6190.9575, 4771.6250, 6050.5039],
        [4898.3472, 2483.6555, 4040.8374, 4771.6250, 6671.3008, 6607.6460],
        [6739.4312, 4215.1240, 6906.3086, 6050.5039, 6607.6460, 8469.8154]])

In [35]:
c.size()

torch.Size([6, 6])

Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [59]:
x = torch.Tensor([1])
x.requires_grad = True
z = torch.Tensor([0.5])
z.requires_grad = True
t = torch.Tensor([2])
t.requires_grad = True
y = x**3 + z - 75*t

In [60]:
y.backward()

In [61]:
x.grad

tensor([3.])

In [63]:
z.grad

tensor([1.])

In [64]:
t.grad

tensor([-75.])

Создайте единичный тензор размера 5x6

In [65]:
ones = torch.ones(5,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

Переведите его в формат numpy

In [67]:
ones.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)